title:            Fun
description:      Try and learn. Just for fun.
url:              http://flydom.github.io# Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Fun # Your name.
disqus_shortname: rubyfun# disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         关于
    url:          /about
  - name:         目录
    url:          /index.html
  - name:         分类
    url:          /404.html
  - name:         Feed
    url:          /feed.xml
  - name:         CSDN
    url:          http://blog.csdn.net/fzy0201
    external:     true
  - name:         GitHub
    url:          http://github.com/flydom
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
