# Site settings
title: Fun
email: fzy0201k@126.com
description: > # this means to ignore newlines until "baseurl:"
  This still is a test blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flydom.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  flydom

# Build settings
markdown: kramdown

permalink: 'pretty'

keep_files: [".git", ".nojekyll"]


